export enum Grades {
  TGOF = 'TGOF',
  BPS = 'BPS',
  BOP = 'BOP',
  BOPSM = 'BOPSM',
  BP = 'BP',
  BPSM = 'BPSM',
  PF = 'PF',
  PD = 'PD',
  DUST = 'DUST',
  CD = 'CD',
  BPS1 = 'BPS1',
  BOPL1 = 'BOPL1',
  BOP1 = 'BOP1',
  BOPSM1 = 'BOPSM1',
  BP1 = 'BP1',
  BPSM1 = 'BPSM1',
  PF1 = 'PF1',
  PD1 = 'PD1',
  DUST1 = 'DUST1',
  CD1 = 'CD1',
  OF = 'OF',
  BOPL = 'BOPL'
}
